# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'day14网易新闻' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'AFNetworking'
pod 'SDWebImage'
pod 'FMDB'
pod 'Masonry'
pod 'YYModel'

  # Pods for day14网易新闻

end
